services:
  - type: web
    name: autoReceipt
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OLLAMA_REMOTE_HOST
        sync: false
      - key: FORMSPREE_ENDPOINT
        sync: false
